#!/bin/bash

# Checks to see if homepage is up
WEB=$(curl limecast.com | grep "Want to broadcast your own show")
if [ "$WEB" = "" ]; then
  echo "" | mail -s "Error: Homepage not accessible" spotdev@limewire.com
fi

# Checks to see if god is running
GOD=$(ps aux | grep god | grep -v grep)
if [ "$GOD" = "" ]; then
  echo "" | mail -s "Error: God not running" spotdev@limewire.com
fi

# Makes sure the disk usage is below 90%
DISK_USAGE=$(df ~/limecast.com/shared | grep "/$" | awk '{ print ($4 > 90) }')
if [ "$DISK_USAGE" = "1" ]; then
  echo "" | mail -s "Error: Disk is more than 90% full" spotdev@limewire.com
fi

