#!/usr/bin/env ruby
root_path = File.join(File.dirname(__FILE__), '..')
require "#{root_path}/config/environment.rb"

stat = Statistic.create(:podcasts_count => Podcast.all.size,
  :podcasts_found_by_admins_count       => Podcast.found_by_admin.size,
  :podcasts_found_by_nonadmins_count    => Podcast.found_by_nonadmin.size,
  :feeds_count                          => Feed.all.size,
  :feeds_found_by_admins_count          => Feed.found_by_admin.size, 
  :feeds_found_by_nonadmins_count       => Feed.found_by_nonadmin.size, 
  :users_count                          => User.all.size,
  :users_active_count                   => User.active.size,
  :users_pending_count                  => User.pending.size,
  :users_passive_count                  => User.passive.size,
  :reviews_count                        => Review.all.size,
  :feeds_from_trackers_count            => Feed.from_limetracker.size,
  :podcasts_with_buttons_count          => Podcast.find_all_by_button_installed(true).size,
  :podcasts_on_google_first_page_count  => 0)
