#!/usr/bin/env ruby
root_path = File.join(File.dirname(__FILE__), '..')
require "#{root_path}/config/environment.rb"

Tagging.
  created_at_least(20.minutes.ago).
  select(&:unclaimed?).
  map(&:destroy)

