#!/usr/bin/env ruby
root_path = File.join(File.dirname(__FILE__), '..')
require "#{root_path}/config/environment.rb"

Podcast.all.each do |p|
  qf = QueuedFeed.find_or_initialize_by_url(p.url)
  qf.update_attributes(
    :state      => p.state || "parsed",
    :error      => p.error,
    :podcast_id => p.id
  )
  puts "QF setup for #{p.title}: errors? #{qf.errors.inspect}\n"
end

