#!/usr/bin/env ruby
root_path = File.join(File.dirname(__FILE__), '..')
require "#{root_path}/config/environment.rb"

Podcast.all.each do |p|
  qp = QueuedPodcast.find_or_initialize_by_url(p.url)
  qp.update_attributes(
    :state      => p.state || "parsed",
    :error      => p.error,
    :podcast_id => p.id
  )
end
