#!/usr/bin/env ruby
root_path = File.join(File.dirname(__FILE__), '..')
require "#{root_path}/config/environment.rb"

Podcast.find(:all).each do |podcast|
  begin
    puts "Getting episodes for #{podcast.title}"
    podcast.feed.fetch
    podcast.feed.parse
    podcast.feed.save!
    podcast.save!
  rescue StandardError => e
    puts "There was a problem: #{e.message}"
  end
end
