#!/usr/bin/env ruby
root_path = File.join(File.dirname(__FILE__), '..')
require "#{root_path}/config/environment.rb"

begin 
  podcast = Podcast.find(ARGV[0])
  puts "Getting archived episodes for #{podcast.title}"
  qf = podcast.queued_feed || podcast.create_queued_feed
  PodcastProcessor.process_archives(qf)
rescue Exception => e
  puts "There was a problem: #{e.message}"
end