#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'

Daemons.run(
  File.join(File.dirname(__FILE__), 'update_sources'),
  :dir_mode => :script,
  :dir      => File.join(File.dirname(__FILE__), '../tmp/pids')
)
