#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), '..', 'config', 'environment')
require 'logger'
@logger = Logger.new(RAILS_ROOT + "/log/update_sources.log")

if(ARGV[0])
  source = Source.find(ARGV[0])
  SourceProcessor.process_source(source, @logger)
  exit
end

while true
  # Sleep 30 minutes until a source is found
  sleep 30.minutes.to_i until source = Source.stale.approved.find(:first, :order => "id DESC")
  SourceProcessor.process_source(source, @logger)
end
